#!/usr/bin/env php
<?php

require __DIR__.'/bootstrap.php';

use System\Console\Console;

Console::register(system_path('Console/Commands'));
Console::register(app_path('Console/Commands'));

Console::listen($argv);
